In [1]:
import numpy as np

![](https://i.imgur.com/jabkxNt.jpg)

In [2]:
R1 = [7.46021406, 2.58905189, 5.9320024,  3.06165002, 2.56025736, 3.82164765]
R2 = [1.17798222, 5.7311303,  3.49258011, 6.36339684, 5.70202671, 3.82134471]
R3 = [-1.96368164,  3.69437634,  3.492642 ,   3.22182489, -0.58032233,  3.82173555]

In [3]:
R4 = [0, 0, 0, 0, 0, 0]
R5 = [0, 2*np.pi, np.pi, 0, np.pi, np.pi]
R6 = [-np.pi, -np.pi, -np.pi, 0, 0, 0]

In [4]:
def rotations_equal(R1, R2):
    R1 = list(map(lambda x: x%(2*np.pi), R1))
    R2 = list(map(lambda x: x%(2*np.pi), R2))
    
    r = lambda i: R1[i]+R2[i]-2*(np.round(R1[i]-R2[i], 2)%np.round(np.pi, 2) == 0)*R2[i] 
    
    rd1 = np.round(np.round(r(0)+r(5), 2)%np.round(2*np.pi, 2), 2)
    rd2 = np.round(np.round(r(1)+r(4), 2)%np.round(2*np.pi, 2), 2)
    rd3 = np.round(np.round(r(2)+r(3), 2)%np.round(2*np.pi, 2), 2)
    
    r = (rd1+rd2+rd3)%(3*np.round(np.pi,2))

    return round(r, 1) == 0

In [5]:
rotations_equal(R1, R2), rotations_equal(R2, R3), rotations_equal(R1, R3)

(True, True, True)

In [6]:
rotations_equal(R4, R5), rotations_equal(R4, R6), rotations_equal(R5, R6)

(True, True, True)

In [7]:
rotations_equal(R1, R5), rotations_equal(R1, R6), rotations_equal(R2, R4)

(False, False, False)

In [8]:
rotations_equal(R1, R4), rotations_equal(R2, R4), rotations_equal(R2, R5)

(False, False, False)

---

## Test with Alignment methods

In [1]:
import sys
sys.path.append("..") 
from oml.alignment import update_quaternion
from oml.angles import quaternion2euler, euler2quaternion

In [10]:
ang = [1.0, 2.0, 3.0]

rotation = [np.array([0, 2*np.pi, np.pi, 0, np.pi, np.pi], dtype=np.float64)]

qp = euler2quaternion(np.array([ang], dtype=np.float64))

qpa = update_quaternion(m=[1.0,1.0,1.0,1.0], 
                        a_R=rotation, 
                        q_predicted=qp)

angles_predicted = quaternion2euler(qpa).numpy()

angles_predicted

array([[1., 2., 3.]])

In [11]:
ang = [1.0, 2.0, 3.0]

rotation = [np.array([np.pi, np.pi, np.pi, np.pi, np.pi, np.pi], dtype=np.float64)]

qp = euler2quaternion(np.array([ang], dtype=np.float64))

qpa = update_quaternion(m=[1.0,1.0,1.0,1.0], 
                        a_R=rotation, 
                        q_predicted=qp)

angles_predicted = quaternion2euler(qpa).numpy()

angles_predicted

array([[1., 2., 3.]])

In [12]:
ang = [1.0, 2.0, 3.0]

rotation = [np.array(R1, dtype=np.float64)]

qp = euler2quaternion(np.array([ang], dtype=np.float64))

qpa = update_quaternion(m=[1.0,1.0,1.0,1.0], 
                        a_R=rotation, 
                        q_predicted=qp)

angles_predicted = quaternion2euler(qpa).numpy()

angles_predicted

array([[ 2.29822589,  2.94827061, -2.48492839]])

In [13]:
ang = [1.0, 2.0, 3.0]

rotation = [np.array(R2, dtype=np.float64)]

qp = euler2quaternion(np.array([ang], dtype=np.float64))

qpa = update_quaternion(m=[1.0,1.0,1.0,1.0], 
                        a_R=rotation, 
                        q_predicted=qp)

angles_predicted = quaternion2euler(qpa).numpy()

angles_predicted

array([[ 2.29429832,  2.94822796, -2.49014507]])

In [14]:
ang = [1.0, 2.0, 3.0]

rotation = [np.array(R3, dtype=np.float64)]

qp = euler2quaternion(np.array([ang], dtype=np.float64))

qpa = update_quaternion(m=[1.0,1.0,1.0,1.0], 
                        a_R=rotation, 
                        q_predicted=qp)

angles_predicted = quaternion2euler(qpa).numpy()

angles_predicted

array([[ 2.30144463,  2.94862414, -2.48245127]])